### ISSUE TITLE
Media Queries don't work

### ISSUE THREAD

**Issue by MicheleBertoli** [krasimir/react-cssx#1]
Thank you very much for you library, it looks very promising.
I was trying it to add it to [my repo](https://github.com/MicheleBertoli/css-in-js) and I found out that while the loader works with Media Queries, the react-cssx component doesn't.

The example n. 1 has the following css:

``` css
h1 {
  color: {{ this.state ? this.state.color : '#000' }};
}
h1 i {
  text-decoration: underline;
}
```

Which is compiled into:

``` css
#cssx-el-2 h1{color:#000;}#cssx-el-2 h1 i{text-decoration:underline;}
```

If I add a simple media query, like:

``` css
@media (max-width: 600px) {
  h1 {
    color: red;
  }
}
```

The CSS looks like this (which is wrong):

``` css
#cssx-el-2 h1{color:red;}#cssx-el-2 h1 i{text-decoration:underline;}
```

**Comment by krasimir** [comment]
Thanks for reporting this. I'll address the problem probably today.

**Comment by krasimir** [comment]
@MicheleBertoli the issue is fixed. Now the output of 

```
css() {
  return (
    <style>
      h1 {
        color: {{ this.state ? this.state.color : '#000' }};
      }
      h1 i {
        text-decoration: underline;
      }
      @media (max-width: 600px) {
        h1 {
          color: red;
        }
      }
    </style>
  );
}
```

is

``` css
#cssx-el-2 h1{color:#000;}#cssx-el-2 h1 i{text-decoration:underline;}@media (max-width: 600px){#cssx-el-2 h1{color:red;}}
```

which is actually:

``` css
#cssx-el-2 h1 {
    color: #000;
}
#cssx-el-2 h1 i {
    text-decoration: underline;
}
@media (max-width: 600px) {
    #cssx-el-2 h1 {
        color: red;
    }
}
```

There is a new `1.0.3` version released. Let me know if it works for you.
