### ISSUE TITLE
Incorrect use of commas

### ISSUE THREAD

**Issue by zvictor** [krasimir/react-cssx#12]
When using commas in my projects, the generated css is not the one I would expect, leading to "leaking" of the styles.

**Input**

``` css
div, span {
  color: black;
}
```

**Expected output**

``` css
#cssx-el-1 div, #cssx-el-1 span {
  color: black;
}
```

**Actual output**

``` css
#cssx-el-1 div, span {
  color: black;
}
```
